[package]
name = "visgrok"
description = "From-scratch driver and real-time analysis for Sipeed SLogic logic analyzers"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
compcol = { version = "0.7.2", default-features = false, features = ["alloc", "zstd", "deflate"] }
rawusb.workspace = true
